name: Built
on:
  push:
    branches: [main]
    
jobs:
  built:
    name: Built & Test
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest,ubuntu-latest]
    steps:
      - name: Get the Source
        uses: actions/checkout@v1
      - name: Restore the dependencies
        run: npm ci
      - name: Built
        run: npm run all